SweetSavory/Models/Treat.cs
using System.Collections.Generic;

namespace SweetSavory.Models
{
  public class Treat
  {
    public Treat()
    {
      this.Flavors = new HashSet<TreatFlavor>();
    }

    public int TreatId { get; set; }
    public string TreatName { get; set; }
    public string Description {get; set; }
    public virtual ApplicationUser User { get; set; }
    public virtual ICollection<TreatFlavor> Flavors { get; set; }
  }
}

SweetSavory/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using SweetSavory.Models;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace SweetSavory.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly SweetSavoryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, SweetSavoryContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    public ActionResult Index()
    {
      return View(_db.Flavors.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Flavor flavor)
    {
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors
        .Include(flavor => flavor.Treats)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      var joinEntry = _db.TreatFlavor.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavor.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

SweetSavory/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using SweetSavory.Models;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace SweetSavory.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly SweetSavoryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, SweetSavoryContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Treats.ToList());
    }

     public ActionResult Create()
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Treat treat, Flavor flavor, int FlavorId)
    {
      _db.Treats.Add(treat);
      if(FlavorId != 0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { FlavorId = FlavorId, TreatId = treat.TreatId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
        .Include(treat => treat.Flavors)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat, int FlavorId)
    {
      if(FlavorId != 0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { FlavorId = FlavorId, TreatId = treat.TreatId});
      }
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.TreatFlavor.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavor.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddFlavor(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int FlavorId)
    {
      if(FlavorId != 0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { FlavorId = FlavorId, TreatId = treat.TreatId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

SweetSavory/Views/Treats/AddFlavor.cshtml
@model SweetSavory.Models.Treat;

<h1>Add flavor to treat</h1>

<h3>Adding flavor to @Html.DisplayFor(model => model.TreatName)</h3>

@using(Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.Label("Select flavor")
  @Html.DropDownList("FlavorId")

  <input type="submit" value="save">
}

<p>@Html.ActionLink("Back to list of treats", "Index")</p>
<p>@Html.ActionLink("Back to home", "Index", "Home")</p>

SweetSavory/Views/Treats/Create.cshtml
@model SweetSavory.Models.Treat

<h1>Add a new treat</h1>

@using(Html.BeginForm())
{
  @Html.LabelFor(model => model.TreatName)
  @Html.TextBoxFor(model => model.TreatName)

  <input type="submit" value="add new treat">
}

<p>@Html.ActionLink("Back to treat list", "Index")</p>
<p>@Html.ActionLink("Back to home", "Index", "Home")</p>

SweetSavory/Views/Treats/Delete.cshtml
@model SweetSavory.Models.Treat

<h2>Are you sure you want to delete this treat?</h2>

<h3>@Html.DisplayNameFor(model => model.TreatName): @Html.DisplayFor(model => model.TreatName)</h3>
@using(Html.BeginForm())
{
  <input type="submit" value="Delete">
}

<p>@Html.ActionLink("Back to treat list", "Index")</p>
<p>@Html.ActionLink("Back to home", "Index", "Home")</p>

SweetSavory/Views/Treats/Details.cshtml
@model SweetSavory.Models.Treat;

<h1>Treat details</h1>
<hr>
<h3>@Html.DisplayFor(model => model.TreatName)</h3>
<hr>

@if(@Model.Flavors.Count == 0)
{
  <p>This treat does not have any flavors listed</p>
}
else
{
  <h3>Flavors</h3>
  @foreach(var join in Model.Flavors)
  {
    @using (Html.BeginForm("DeleteFlavor", "Treats"))
    {
      <p>@Html.ActionLink($"{join.Flavor.FlavorName}", "Details", "Flavors", new { id = join.Flavor.FlavorId })</p><br>
      @Html.Hidden("joinId", @join.TreatFlavorId)
      <input type="submit" value="x"/>
    }
  }
}
<br><br>

<p>@Html.ActionLink("Edit this treat", "Edit", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Delete this treat", "Delete", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Add an flavor to this treat", "AddFlavor", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Back to treat list", "Index")</p>
<p>@Html.ActionLink("Back to home", "Index", "Home")</p>

SweetSavory/Views/Treats/Edit.cshtml
@model SweetSavory.Models.Treat

<h1>Edit treat</h1>
<h4>Treat being edited: @Html.DisplayFor(model => model.TreatName)</h4>

@using(Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.LabelFor(model => model.TreatName)
  @Html.EditorFor(model => model.TreatName)
  <br>
  @Html.Label("Select flavor")
  @Html.DropDownList("FlavorId")

  <input type="submit" value="save">
}

<p>@Html.ActionLink("Back to treat list", "Index")</p>
<p>@Html.ActionLink("Back to home", "Index", "Home")</p>

SweetSavory/Views/Treats/Index.cshtml
@using SweetSavory.Models;
@model List<SweetSavory.Models.Treat>;

<h1>Treats available</h1>
<hr>

@if(@Model.Count == 0)
{
  <h3>No treats to list</h3>
}
<ul>
  @foreach(Treat treat in Model)
  {
    <li>@Html.ActionLink($"{treat.TreatName}", "Details", new { id = treat.TreatId })</li>
  }
</ul>
<hr>

<p>@Html.ActionLink("Add new treat", "Create")</p>
<p>@Html.ActionLink("Back to home", "Index", "Home")</p>